name: Linters

on:
  pull_request: {}
  push: {}

jobs:
  gitlint:
    runs-on: ubuntu-latest
    name: GitLint
    steps:
      - uses: actions/checkout@v2
        with:
          # Check out at the last commit (pre-automated merge, we don't care about the temporary commit for linting)
          ref: ${{ github.event.pull_request.head.sha }}
          # Get all history
          fetch-depth: 0
      
      - name: Install gitlint
        shell: bash
        run: |
          python -m pip install gitlint
        
      - name: Run gitlint file
        shell: bash
        run: |
          # Lint everything from base to the latest
          gitlint --commits "${{ github.event.pull_request.base.sha }} ..HEAD"
